# -*- coding: utf-8 -*-
"""DTA-Temp-Vt-convert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17oomPAhIrtTtKWMWu0zGtUMeQFjhXkpZ
"""

#DTA関数
#-9500<Vt<-8025
def Region1(Vt):
  T=2215.71556+.7279584164*Vt+8.6987279178*10**(-5)*Vt**2+3.628145299*10**(-9)*Vt**3
  return T

#-8025<Vt<-6200
def Region2(Vt):
  T=351.9516207+.05462261832*Vt+5.836711682*10**(-6)*Vt**2+3.652376504*10**(-10)*Vt**3
  return T

#6200<Vt<-3950
def Region3(Vt):
  T=277.3823785+.02011218159*Vt+4.949648236*10**(-7)*Vt**2+8.859387968*10**(-11)*Vt**3
  return T

#-3950<Vt<-1360
def Region4(Vt):
  T=273.5617264+0.01765379968*Vt+7.137919542*10**(-9)*Vt**2+6.116704187*10**(-11)*Vt**3
  return T

#-1360<Vt<1640
def Region5(Vt):
  T=273.1534526+.01705349031*Vt-2.797508035*10**(-7)*Vt**2+1.501272037*10**(-11)*Vt**3
  return T

#1640<Vt<4840
def Region6(Vt):
  T=273.1973681+.01699032605*Vt-2.448421881*10**(-7)*Vt**2+7.25590263*10**(-12)*Vt**3
  return T

#4840<Vt<8400
def Region6(Vt):
  T=273.5651668+.01676422623*Vt-1.976262268*10**(-7)*Vt**2+3.906447737*10**(-12)*Vt**3
  return T

def Region7(Vt):
  T=273.5651668+.01676422623*Vt-1.976262268*10**(-7)*Vt**2+3.906447737*10**(-12)*Vt**3
  return T

def VtToTemp(Vt):
  if (Vt>=-9500 and Vt<-8025):
    return Region1(Vt)
  elif (Vt>=-8025 and Vt<=-6200):
    return Region2(Vt)
  elif (Vt>=-6200 and Vt<=-3950):
     return Region3(Vt)
  elif (Vt>=-3950 and Vt<=-1360):
     return Region4(Vt)
  elif Vt>=-1360 and Vt<=1640:
     return Region5(Vt)
  elif Vt>=1640 and Vt<=4840:
     return Region6(Vt)
  elif Vt>=4840 and Vt<=8400:
     return Region7(Vt)
    
# import Keigetpv
# import time
# while True:
#     Vt2000 = Keigetpv.getPv2000()
#     #Vt2182A = Keigetpv.getPv2182A()
#     Vt2000 = float(Vt2000)
#     print(Vt2000*1000000)
#     #Vt2182A = float(Vt2182A)
#     print(VtToTemp(1000000*Vt2000))
#     #print(VtToTemp(Vt2182A))
#     time.sleep(1)
    
